<?php

namespace ALajusticia\AuthTracker\Tests;

use ALajusticia\AuthTracker\AuthTrackerServiceProvider;
use ALajusticia\Expirable\ExpirableServiceProvider;
use Laravel\Airlock\AirlockServiceProvider;
use Laravel\Passport\PassportServiceProvider;

abstract class TestCase extends \Orchestra\Testbench\TestCase
{
    /**
     * Setup the test environment.
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp();

        $this->loadLaravelMigrations();

        $this->artisan('migrate')->run();

        $this->withFactories(__DIR__.'/database/factories');
    }

    /**
     * Get package providers.
     *
     * @param  \Illuminate\Foundation\Application  $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            AuthTrackerServiceProvider::class,
            ExpirableServiceProvider::class,
            PassportServiceProvider::class,
            AirlockServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub
    }
}
